services:
    web:
        image: nginx:1.17-alpine
        container_name: web
        ports:
            - '80:80'
        volumes:
            - ./:/var/www/html
            - ./config/default.conf:/etc/nginx/conf.d/default.conf

    app:
        image: jonathanxribeiro/phpnextgen:1.0.0
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/html
            - ./config/php.ini:/usr/local/etc/php/php.ini

    db:
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: next-gen
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
        volumes:
            - pg_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
  pg_data:       

            